# Generated by Django 5.1.4 on 2025-03-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredsaree',
            name='product_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
